import type { DashboardOverview } from "@/features/dashboard/model/types";

/** Sample payload for demos / design reviews when `VITE_DASHBOARD_DEMO=true`. */
export const mockDashboardOverview: DashboardOverview = {
  stats: {
    totalStudents: 1284,
    totalTeachers: 86,
    activeGroups: 42,
    overduePayments: 7,
  },
  todayLessons: [
    {
      id: "1",
      startsAt: new Date().toISOString().replace(/T.*$/, "T08:00:00.000Z"),
      endsAt: new Date().toISOString().replace(/T.*$/, "T08:45:00.000Z"),
      subject: "Mathematics",
      room: "A-201",
      groupName: "Grade 10-A",
      teacherName: "Samira Karimova",
    },
    {
      id: "2",
      startsAt: new Date().toISOString().replace(/T.*$/, "T09:00:00.000Z"),
      endsAt: new Date().toISOString().replace(/T.*$/, "T09:45:00.000Z"),
      subject: "English",
      room: "B-104",
      groupName: "Grade 9-B",
      teacherName: "James Okonkwo",
    },
    {
      id: "3",
      startsAt: new Date().toISOString().replace(/T.*$/, "T10:15:00.000Z"),
      endsAt: new Date().toISOString().replace(/T.*$/, "T11:00:00.000Z"),
      subject: "Physics Lab",
      room: "Lab-1",
      groupName: "Grade 11 Sciences",
      teacherName: "Elena Petrov",
    },
    {
      id: "4",
      startsAt: new Date().toISOString().replace(/T.*$/, "T13:00:00.000Z"),
      endsAt: new Date().toISOString().replace(/T.*$/, "T13:45:00.000Z"),
      subject: "History",
      room: "C-310",
      groupName: "Grade 10-B",
      teacherName: "Maria Santos",
    },
  ],
  recentPayments: [
    {
      id: "p1",
      paidAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
      payerName: "Dilnoza Rahimova",
      amountCents: 450_000,
      currency: "UZS",
      status: "paid",
      reference: "INV-24091",
    },
    {
      id: "p2",
      paidAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
      payerName: "Rustam Toshmatov",
      amountCents: 225_000,
      currency: "UZS",
      status: "paid",
      reference: "INV-24088",
    },
    {
      id: "p3",
      paidAt: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
      payerName: "Madina K.",
      amountCents: 450_000,
      currency: "UZS",
      status: "pending",
      reference: "INV-24085",
    },
    {
      id: "p4",
      paidAt: new Date(Date.now() - 1000 * 60 * 60 * 50).toISOString(),
      payerName: "Jamshid M.",
      amountCents: 112_500,
      currency: "UZS",
      status: "overdue",
      reference: "INV-24070",
    },
    {
      id: "p5",
      paidAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
      payerName: "Nilufar A.",
      amountCents: 450_000,
      currency: "UZS",
      status: "paid",
      reference: "INV-24061",
    },
  ],
  attendanceSummary: [
    {
      id: "a1",
      date: new Date(Date.now() - 86400000 * 1).toISOString(),
      presentCount: 612,
      absentCount: 38,
      lateCount: 14,
      attendanceRate: 0.92,
    },
    {
      id: "a2",
      date: new Date(Date.now() - 86400000 * 2).toISOString(),
      presentCount: 598,
      absentCount: 52,
      lateCount: 18,
      attendanceRate: 0.89,
    },
    {
      id: "a3",
      date: new Date(Date.now() - 86400000 * 3).toISOString(),
      presentCount: 621,
      absentCount: 29,
      lateCount: 11,
      attendanceRate: 0.93,
    },
    {
      id: "a4",
      date: new Date(Date.now() - 86400000 * 4).toISOString(),
      presentCount: 605,
      absentCount: 45,
      lateCount: 22,
      attendanceRate: 0.9,
    },
    {
      id: "a5",
      date: new Date(Date.now() - 86400000 * 5).toISOString(),
      presentCount: 587,
      absentCount: 61,
      lateCount: 19,
      attendanceRate: 0.87,
    },
  ],
  weeklyActivity: [
    { label: "Mon", value: 42 },
    { label: "Tue", value: 55 },
    { label: "Wed", value: 48 },
    { label: "Thu", value: 61 },
    { label: "Fri", value: 53 },
    { label: "Sat", value: 22 },
    { label: "Sun", value: 12 },
  ],
};
